// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIuCu-IfuXsZjy-fTL7phKRTJXV7RkYew',
    appId: '1:379162369299:web:f6db008bb95acb74114ee6',
    messagingSenderId: '379162369299',
    projectId: 'circlelinks-9ac71',
    authDomain: 'circlelinks-9ac71.firebaseapp.com',
    storageBucket: 'circlelinks-9ac71.firebasestorage.app',
    measurementId: 'G-41G8FT62HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABu03-h2Ql-5AOsuiJZn_qOX8VhaEbrms',
    appId: '1:379162369299:android:70a4e0d3dc675861114ee6',
    messagingSenderId: '379162369299',
    projectId: 'circlelinks-9ac71',
    storageBucket: 'circlelinks-9ac71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEdy4KCYCNmCj-h_Rse8u1AqqfwJaCt8',
    appId: '1:379162369299:ios:b6106ab0b37f09ce114ee6',
    messagingSenderId: '379162369299',
    projectId: 'circlelinks-9ac71',
    storageBucket: 'circlelinks-9ac71.firebasestorage.app',
    androidClientId: '379162369299-4a1odiok5ugeu134iq29sl09lh0bjr6g.apps.googleusercontent.com',
    iosClientId: '379162369299-km0h9crt8ll13blrkqnkn1uscdg3j3nk.apps.googleusercontent.com',
    iosBundleId: 'com.circlelink.app.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEdy4KCYCNmCj-h_Rse8u1AqqfwJaCt8',
    appId: '1:379162369299:ios:baddba7e2022dc26114ee6',
    messagingSenderId: '379162369299',
    projectId: 'circlelinks-9ac71',
    storageBucket: 'circlelinks-9ac71.firebasestorage.app',
    androidClientId: '379162369299-4a1odiok5ugeu134iq29sl09lh0bjr6g.apps.googleusercontent.com',
    iosClientId: '379162369299-hgulh64ro7siq905rk7oj0ib83g8155v.apps.googleusercontent.com',
    iosBundleId: 'com.circlelink.circlelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIuCu-IfuXsZjy-fTL7phKRTJXV7RkYew',
    appId: '1:379162369299:web:52da5ce58633a789114ee6',
    messagingSenderId: '379162369299',
    projectId: 'circlelinks-9ac71',
    authDomain: 'circlelinks-9ac71.firebaseapp.com',
    storageBucket: 'circlelinks-9ac71.firebasestorage.app',
    measurementId: 'G-SS4J9SBN3F',
  );

}